### ISSUE TITLE
Working! Can it work with Infinite Zoom?

### ISSUE THREAD

**Issue by ProfitC** [WildBanjos/DiffusionDefender#4]
Im not sure this is an issue but is there a way to make it work with the Infinite Zoom extension as well? Infinite Zoom is fun and I would like to add it to the public side of my server.

PS. DiffusionDefender has been awesome so far and after tuning the .txt file I was able to get some pretty consistantly good looking Donkeys ;) 

Thank you for all you do,
ProfitC

**Comment by WildBanjos** [comment]
Did you intend to close and complete this issue?
